// COMMON
export const INIT_ALL = "INIT_ALL"

export const MENU_FLAG = "MENU_FLAG"

export const SELECT_YEAR = "SELECT_YEAR"
export const SELECT_MONTH = "SELECT_MONTH"
export const PREVIOUS_MONTH = "PREVIOUS_MONTH"
export const NEXT_MONTH = "NEXT_MONTH"
export const SELECT_DATE = "SELECT_DATE"

// USER
export const SAVE_USER_ID = "SAVE_USER_ID"
export const GET_USER_PASSWORD = "GET_USER_PASSWORD"
export const DELETE_USER_ID = "DELETE_USER_ID"
export const UPDATE_USER = "UPDATE_USER"

// GROUP
export const ADD_GROUP = "ADD_GROUP"
export const FETCH_GROUP_NAMES = "FETCH_GROUP_NAMES"
export const FETCH_GROUP_NAMES_ASYNC = "FETCH_GROUP_NAMES_ASYNC"
export const FETCH_GROUP_LIST = "GET_GROUP_LIST"
export const INVITE_TO_GROUP = "INVITE_TO_GROUP"
export const GET_MEMBERS_BY_GROUP = "GET_MEMBERS_BY_GROUP"

// TODO
export const ADD_TODO = "ADD_TODO"
export const UPDATE_TODO = "UPDATE_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const FETCH_TODOS_BY_ID = "FETCH_TODOS_BY_ID"
export const FETCH_TODOS_BY_GROUPID = "FETCH_TODOS_BY_GROUPID"
export const SHOW_TODO_DETAIL = "SHOW_TODO_DETAIL"
export const EXIT_TODO_DETAIL = "EXIT_TODO_DETAIL"

// MESSAGE
export const FETCH_MESSAGES = "FETCH_MESSAGES"
export const UPDATE_MESSAGE_STATUS = "UPDATE_MESSAGE_STATUS"
export const JOIN_GROUP = "JOIN_GROUP"
