// COMMON
export const INIT_ALL = "INIT_ALL"

// USER
export const SAVE_USER_ID = "SAVE_USER_ID"
export const DELETE_USER_ID = "DELETE_USER_ID"
export const UPDATE_USER = "UPDATE_USER"

// GROUP
export const ADD_GROUP = "ADD_GROUP"
export const FETCH_GROUP_NAMES = "FETCH_GROUP_NAMES"
export const FETCH_GROUP_LIST = "GET_GROUP_LIST"
export const INVITE_TO_GROUP = "INVITE_TO_GROUP"
export const GET_MEMBERS_BY_GROUP = "GET_MEMBERS_BY_GROUP"

// TODO
export const ADD_TODO = "ADD_TODO"
export const UPDATE_TODO = "UPDATE_TODO"
export const DELETE_TODO = "DELETE_TODO"

// MESSAGE
export const FETCH_MESSAGES = "FETCH_MESSAGES"
export const UPDATE_MESSAGE_STATUS = "UPDATE_MESSAGE_STATUS"
